Inspection audio warning. Fixes #23
euphwes/cubers.io pull request #141
Opened 2020-10-15 03:32 UTC by marceloFA

This PR adds a new configuration called "Use Inspection Time Audio Warning" which will play a simple beep when 8s and 12s of inspection time have been elapsed. 

I chose to create a draft first as there are some refinements to do before it can be proposed to merge.

@euphwes, would you help me with a small issue I'm having, please? 
The last time I contributed to a change in the app settings (#138), the new setting was automatically created for my dev user after I added it to ``app/persistence/settings_manager.py``. This time this didn't seem to have occurred and the new ``SettingCode.USE_INSPECTION_AUDIO_WARNING ``is not showing up on the ``settings_sections `` OrderedDict at ``app/routes/user/settings_routes.py``. I imagine this is somehow caused by my addition of the new setting into the ``affects`` list of ``SettingCode.USE_INSPECTION_TIME``. Am I missing something on how to implement a new setting that is affected by previously defined settings?

If you want to try out the changes of this PR in the /compete route timer, you can force
```javascript
 this.use_inspection_audio_warning = true;
``` 
instead of 
```javascript
app.userSettingsManager.get_setting(app.Settings.USE_INSPECTION_AUDIO_WARNING);
```
at ``timer_controller.js`` as the standard import of this setting won't currently work.

Thanks!

2020-10-16 15:40 UTC, euphwes commented
Hey sorry I didn't get back to you on this yet. Had a busy day yesterday. I'll pull down your code so far and take a look, and point you in the right direction hopefully later today! Thanks for picking up this task!

2020-10-16 21:55 UTC, euphwes commented
@marceloFA It looks like populating the setting is working properly for me:

1. Right after pulling your code, I visited the timer page. I checked the database for that setting for my user, and it existed (with the correct default `false` value).

2. I deleted that entry from the database. Visited the settings page and changed `Use Inspection Time Audio Warning` to `true` and submitted my change. Checked the database and confirmed the setting was there, with `true` value. Visited the timer page and let the timer run low, and heard the warning chimes after 8 and 12 seconds.

You said:
>as the standard import of this setting won't currently work.

In what way is that not working for you? You turn the setting on, but your timer still doesn't chime?

2020-10-16 22:00 UTC, euphwes requested changes

2020-10-16 22:00 UTC, euphwes commented on app/persistence/settings_manager.py
> +        affects       = [SettingCode.HIDE_INSPECTION_TIME, SettingCode.USE_INSPECTION_AUDIO_WARNING]
This looks right! You used it correctly.

2020-10-17 13:43 UTC, marceloFA commented on app/static/js/timer/timer_controller.js
> +        else if (seconds_remaining < this.AUTO_DNF_THRESHOLD) {
Oh, now I see it! Thanks for this

2020-10-17 13:49 UTC, marceloFA commented
Wes, It looks like populating the setting now is working properly for me too. Unfortunately, I couldn't notice what was going on before that make it didn't work. But at least everything in this PR code is functioning adequately now, in my point of view. 😂

2020-10-18 16:35 UTC, merged