[#151] Pagination on event records
euphwes/cubers.io pull request #160
Opened 2020-12-16 22:32 UTC by marceloFA

hi Wes. Here's a pagination feature to the /events route. Let me know if this was implemented as desired. If so, we can expand the feature to /kinchranks and /sum_of_ranks. 

One important detail: I had no records to populate the rankings and test the pagination feature so if you could, please check it's working properly, please <3

2020-12-22 19:09 UTC, euphwes commented
Hey @marceloFA , so sorry I somehow missed this! I can probably take a look soon, but I think there's a way you can test it too. In `commands.py`, there's a utility command ([generate_fake_comp_results](https://github.com/euphwes/cubers.io/blob/master/app/commands.py#L209-L277)) you can use to fill out the leaderboards for the current comp running. I have like a dozen or so hardcoded names in there, but you could tweak that to have programmatically create 100 or 200 users and submit results for them, which would give you enough data to test your pagination stuff.

Thanks for doing this! I'll look more in-depth in the next couple days, I've just been busy with real life and work lately.

2020-12-22 22:32 UTC, marceloFA commented
Thanks for the tips, Wes.  

It's completely fine if you take some time to review this, don't worry at all. By the way, merry christmas to you 🎅

2021-01-13 23:42 UTC, euphwes commented
@marceloFA I just tried pulling this down and running, but I'm running into some issues already:

```
line 238, in _build_PersonalBestRecord
    username=record.username,
AttributeError: 'UserEventResults' object has no attribute 'username'
```

You can add some bogus results to your local database with the command I mentioned above, and then actually try running this yourself locally. I can come back to this myself later, but I bet the big issues you'll manage to knock out quickly! Thanks again for picking up this task.

2021-01-13 23:49 UTC, euphwes requested changes

2021-01-13 23:49 UTC, euphwes commented on app/business/rankings.py
> +        username=record.username,
This is where it's dying when I try to spin up. The record you're passing in doesn't have a `username` attribute.

2021-01-13 23:49 UTC, euphwes commented on app/business/rankings.py
> -        values(UserEventResults.user_id, UserEventResults.average, Competition.id, Competition.title, User.username, UserEventResults.comment, User.is_verified)
So when you remove this line, you're changing the query to just return a list of `UserEventResults` records. The `values(...)` line says to select the specific values you're specifying.

The SQL for this looks something like

```
SELECT <all those fields I specified>
FROM UserEventResults
INNER JOIN User on UserEventResults.user_id = User.id
INNER JOIN CompetitionEvent ...
INNER JOIN Event ...
```

but removing the `value(...)` line basically just only selects the entire `UserEventResults` record and nothing else from the other tables that are joined in the query.

2021-01-14 00:11 UTC, marceloFA commented
Hi, Wes. Recently I've quite busy with academic tasks so I haven't finished this yet.  My semester is coming to an end in February and then I'll come back to this PR. Thanks for the review and sorry for keeping this open for a while more!

2021-01-14 01:05 UTC, euphwes commented
No worries and no hurry! School comes first, for sure.

2021-01-22 22:54 UTC, merged

2021-01-22 22:56 UTC, euphwes commented
Oops, somehow merged this when I didn't intend to. I'll fix my commit history and force push, and then see if I can re-open this. @marceloFA

2021-01-22 23:04 UTC, euphwes commented
@marceloFA Ok I fixed accidentally pushing this code (and therefore merging this pull request), but I can't seem to re-open it. Sorry about that! Whenever your school semester is over and if you still want to pick this back up, you'll need to open another PR.

2021-01-23 19:19 UTC, marceloFA commented
No problem, Wes! :D